version = 1

[*]
temp=0.1
ctx-size=32768
n-gpu-layers=99

;QWEN

[unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF]
hf=unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF
n-cpu-moe=99

[unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF]
hf=unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF
n-cpu-moe=99

[unsloth/Qwen3-4B-Instruct-2507-GGUF]
hf=unsloth/Qwen3-4B-Instruct-2507-GGUF

[unsloth/Qwen3-1.7B-GGUF]
hf=unsloth/Qwen3-1.7B-GGUF

[unsloth/Qwen3-0.6B-GGUF]
hf=unsloth/Qwen3-0.6B-GGUF

;MISTRAL

[unsloth/Ministral-3-14B-Instruct-2512-GGUF]
hf=unsloth/Ministral-3-14B-Instruct-2512-GGUF

[unsloth/Ministral-3-8B-Instruct-2512-GGUF]
hf=unsloth/Ministral-3-8B-Instruct-2512-GGUF

[unsloth/Ministral-3-3B-Instruct-2512-GGUF]
hf=unsloth/Ministral-3-3B-Instruct-2512-GGUF

; [unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF]
; hf=unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF
; temp=0.15
; min-p=0.01
