version = 1

[*]
parallel=1
fit-target=64
fit-ctx=64
temp=0.5
ctx-size=128000
jinja=on
fit=on
seed=3407
threads=5
cache-type-k=q8_0
cache-type-v=q8_0
cache-type-k-draft=q8_0
cache-type-v-draft=q8_0
flash-attn=on
no-mmap=on

;GEMMA

[unsloth/gemma-4-26B-A4B-it-GGUF]
hf=unsloth/gemma-4-26B-A4B-it-GGUF
temperature=1.0
top-p=0.95
top-k=64
ctx-size=256000

;QWEN

[unsloth/Qwen3.5-35B-A3B-GGUF]
hf=unsloth/Qwen3.5-35B-A3B-GGUF
chat-template-kwargs={"enable_thinking": false}
top-p=0.95
top-k=20
min-p=0.00

[unsloth/Qwen3.5-think-35B-A3B-GGUF]
hf=unsloth/Qwen3.5-35B-A3B-GGUF
chat-template-kwargs={"enable_thinking": true}
top-p=0.95
top-k=20
min-p=0.00
presence-penalty=1.5

[unsloth/Qwen3.5-9B-GGUF]
hf=unsloth/Qwen3.5-9B-GGUF
top-p=0.95
top-k=20
min-p=0.00

[unsloth/Qwen3.5-4B-GGUF]
hf=unsloth/Qwen3.5-4B-GGUF
top-p=0.95
top-k=20
min-p=0.00

[unsloth/Qwen3.5-2B-GGUF]
hf=unsloth/Qwen3.5-2B-GGUF
top-p=0.95
top-k=20
min-p=0.00

[unsloth/Qwen3.5-0.8B-GGUF]
hf=unsloth/Qwen3.5-0.8B-GGUF
chat-template-kwargs={"enable_thinking": false}
top-p=0.95
top-k=20
min-p=0.00
presence-penalty=1.5

;MISTRAL

; [unsloth/Ministral-3-8B-Instruct-2512-GGUF]
; hf=unsloth/Ministral-3-8B-Instruct-2512-GGUF

; [unsloth/Ministral-3-3B-Instruct-2512-GGUF]
; hf=unsloth/Ministral-3-3B-Instruct-2512-GGUF

; [unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF]
; hf=unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF
; temp=0.15
; min-p=0.01
