services:
    app:
        container_name: llama-server
        image: ghcr.io/ggml-org/llama.cpp:server-vulkan
        restart: unless-stopped
        ports:
            - 9090:8080
        networks:
            - dev
        volumes:
            - ./models:/root/.cache/huggingface/hub
            - ./config.ini:/app/config.ini:ro
        devices:
            - /dev/dri
        entrypoint: ["/app/llama-server", "--models-preset", "config.ini"]

networks:
    dev:
        external: true
