services:
    app:
        container_name: llama-server
        image: ghcr.io/ggml-org/llama.cpp:server-vulkan
        restart: unless-stopped
        ports:
            - 9090:8080
        networks:
            - dev
        volumes:
            - ./models:/root/.cache/llama.cpp/
            - ./config.ini:/app/config.ini:ro
        devices:
            - /dev/dri
        entrypoint: ["/app/llama-server", "--models-preset", "config.ini"]
    # mcp:
    #     container_name: inspector
    #     image: ghcr.io/modelcontextprotocol/inspector
    #     ports:
    #         - 6274:6274
    #         - 6277:6277
    #     networks:
    #         - dev
    #     environment:
    #         - HOST=0.0.0.0
    #         - MCP_AUTO_OPEN_ENABLED=false
    #         - DANGEROUSLY_OMIT_AUTH=true

networks:
    dev:
        external: true
